/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DonationWidget {
        "merchant_key": string;
    }
    interface PayboxCheckoutWidget {
        "amount": number;
        "beneficiary_name"?: string;
        "currency": string;
        "customer_id"?: number;
        "email": string;
        "merchant_key": string;
        "order_id"?: number;
        "payer_name": string;
        "payer_phone": string;
        "payload"?: string;
        "phone_number": string;
        "redirect_url"?: string;
        "reload"?: boolean;
    }
    interface PayboxDonationWidget {
        "email": string;
        "merchant_key": string;
        "payer_name": string;
        "payer_phone": string;
    }
}
export interface PayboxCheckoutWidgetCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPayboxCheckoutWidgetElement;
}
declare global {
    interface HTMLDonationWidgetElement extends Components.DonationWidget, HTMLStencilElement {
    }
    var HTMLDonationWidgetElement: {
        prototype: HTMLDonationWidgetElement;
        new (): HTMLDonationWidgetElement;
    };
    interface HTMLPayboxCheckoutWidgetElementEventMap {
        "didReset": any;
    }
    interface HTMLPayboxCheckoutWidgetElement extends Components.PayboxCheckoutWidget, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPayboxCheckoutWidgetElementEventMap>(type: K, listener: (this: HTMLPayboxCheckoutWidgetElement, ev: PayboxCheckoutWidgetCustomEvent<HTMLPayboxCheckoutWidgetElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPayboxCheckoutWidgetElementEventMap>(type: K, listener: (this: HTMLPayboxCheckoutWidgetElement, ev: PayboxCheckoutWidgetCustomEvent<HTMLPayboxCheckoutWidgetElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPayboxCheckoutWidgetElement: {
        prototype: HTMLPayboxCheckoutWidgetElement;
        new (): HTMLPayboxCheckoutWidgetElement;
    };
    interface HTMLPayboxDonationWidgetElement extends Components.PayboxDonationWidget, HTMLStencilElement {
    }
    var HTMLPayboxDonationWidgetElement: {
        prototype: HTMLPayboxDonationWidgetElement;
        new (): HTMLPayboxDonationWidgetElement;
    };
    interface HTMLElementTagNameMap {
        "donation-widget": HTMLDonationWidgetElement;
        "paybox-checkout-widget": HTMLPayboxCheckoutWidgetElement;
        "paybox-donation-widget": HTMLPayboxDonationWidgetElement;
    }
}
declare namespace LocalJSX {
    interface DonationWidget {
        "merchant_key"?: string;
    }
    interface PayboxCheckoutWidget {
        "amount"?: number;
        "beneficiary_name"?: string;
        "currency"?: string;
        "customer_id"?: number;
        "email"?: string;
        "merchant_key"?: string;
        "onDidReset"?: (event: PayboxCheckoutWidgetCustomEvent<any>) => void;
        "order_id"?: number;
        "payer_name"?: string;
        "payer_phone"?: string;
        "payload"?: string;
        "phone_number"?: string;
        "redirect_url"?: string;
        "reload"?: boolean;
    }
    interface PayboxDonationWidget {
        "email"?: string;
        "merchant_key"?: string;
        "payer_name"?: string;
        "payer_phone"?: string;
    }
    interface IntrinsicElements {
        "donation-widget": DonationWidget;
        "paybox-checkout-widget": PayboxCheckoutWidget;
        "paybox-donation-widget": PayboxDonationWidget;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "donation-widget": LocalJSX.DonationWidget & JSXBase.HTMLAttributes<HTMLDonationWidgetElement>;
            "paybox-checkout-widget": LocalJSX.PayboxCheckoutWidget & JSXBase.HTMLAttributes<HTMLPayboxCheckoutWidgetElement>;
            "paybox-donation-widget": LocalJSX.PayboxDonationWidget & JSXBase.HTMLAttributes<HTMLPayboxDonationWidgetElement>;
        }
    }
}
